import images from "./images";

const menu = [
  {
    id: 1,
    title: "E-commerce",
    category: "Next",
    url: "https://ecom-muhats.vercel.app/",
    source: "https://github.com/coolzyte/ecommerce_sanity_stripe",
    tags: ["NextJS", "Sanity", "Stripe"],
    img: `${images.p9}`,
    desc: "E-commerce App",
  },

  {
    id: 2,
    title: "Realtor",
    category: "react",
    url: "https://realtor-muhammedtijani.vercel.app/",
    source: "https://github.com/muhammedtijani/realtor",
    tags: ["React/Next", "ChakraUI"],
    img: `${images.p2}`,
    desc: `Real estate app`,
  },
  {
    id: 3,
    title: "Startup",
    category: "react",
    url: "https://startup.muhats.com/",
    source: "https://github.com/coolzyte/startup",
    tags: ["React", "Tailwind"],
    img: `${images.p3}`,
    desc: `Startup focus template`,
  },
  {
    id: 4,
    title: "Crypto News",
    category: "mern",
    url: "https://cryptoverse.muhats.com/",
    source: "https://github.com/muhammedtijani/cryptonews",
    tags: ["React", "Tailwind"],
    img: `${images.p1}`,
    desc: "Crypto News App",
  },
  {
    id: 5,
    title: "Portfolio",
    category: "react",
    url: "https://portfolio-v-1.muhats.com/",
    source: "",
    tags: ["React", "styled-component"],
    img: `${images.p7}`,
    desc: `modern portfolio template`,
  },
  {
    id: 6,
    title: "Search App",
    category: "react",
    url: "https://goggle.muhats.com/search",
    source: "",
    tags: ["React", "Tailwind"],
    img: `${images.p8}`,
    desc: "Search App",
  },
  {
    id: 7,
    title: "Restaurant",
    category: "react",
    url: "https://restaurant.coolzyte.com/",
    source: "https://github.com/muhammedtijani/restaurant",
    tags: ["React", "CSS"],
    img: `${images.p4}`,
    desc: `Restaurant website template `,
  },
];
export default menu;
