import images from './images';

const menu = [
  {
    id: 1,
    title: 'E-commerce',
    category: 'Next',
    url: 'https://ecom-muhats.vercel.app/',
    source: 'https://github.com/coolzyte/ecommerce_sanity_stripe',
    tags: ['NextJS', 'Sanity', 'Stripe'],
    img: `${images.p9}`,
    desc: 'E-commerce App',
  },

  {
    id: 2,
    title: 'Realtor',
    category: 'Next',
    url: 'https://realtor-muhammedtijani.vercel.app/',
    source: 'https://github.com/muhammedtijani/realtor',
    tags: ['NextJS', 'ChakraUI'],
    img: `${images.p2}`,
    desc: `Real estate app`,
  },
  {
    id: 3,
    title: 'Ecom',
    category: 'react',
    url: 'https://ecom2.muhats.com/home',
    source: 'https://github.com/coolzyte/elysi-commerce',
    tags: ['React', 'TailwindCSS'],
    img: `${images.p19}`,
    desc: `E-commerce app`,
  },
  {
    id: 4,
    title: 'Job Board',
    category: 'react',
    url: 'https://job-board.muhats.com',
    source: 'https://github.com/coolzyte/job-board',
    tags: ['React', 'Tailwind CSS'],
    img: `${images.p18}`,
    desc: `Job board app`,
  },

  {
    id: 5,
    title: 'Crypto News',
    category: 'mern',
    url: 'https://crypto-news.muhats.com/',
    source: 'https://github.com/coolzyte/cryptonews',
    tags: ['React', 'MaterialUI'],
    img: `${images.p1}`,
    desc: 'Crypto News App',
  },

  // {
  //   id: 6,
  //   title: 'Search App',
  //   category: 'react',
  //   url: 'https://goggle.muhats.com',
  //   source: '',
  //   tags: ['React', 'Tailwind'],
  //   img: `${images.p8}`,
  //   desc: 'Search App',
  // },

  {
    id: 7,
    title: 'Image To Text',
    category: 'Typescript',
    url: 'https://image-text.muhats.com/',
    source: 'https://github.com/coolzyte/image-text',
    tags: ['React', 'Typescript', 'TailwindCSS'],
    img: `${images.p20}`,
    desc: `Image to text converter`,
  },
  {
    id: 8,
    title: 'Dev Portfolio',
    category: 'react',
    url: 'https://smato-clone.muhats.com/',
    source: 'https://github.com/coolzyte/smato-clone-react',
    tags: ['React', 'Styled-component', 'TailwindCSS'],
    img: `${images.p13}`,
    desc: `Browse Hotels Around the world `,
  },

  {
    id: 9,
    title: 'Personal Portfolio',
    category: 'react',
    url: 'https://portfolio.muhats.com/',
    source: 'https://github.com/coolzyte/portfolio_v3',
    tags: ['React', 'Typescript', 'Styled-Components'],
    img: `${images.p11}`,
    desc: `Portfolio Template `,
  },
  // {
  //   id: 10,
  //   title: 'Travel Advisor',
  //   category: 'react',
  //   url: 'https://hotelapp.muhats.com/',
  //   source: 'https://github.com/coolzyte/travel_advisor',
  //   tags: ['React', 'RapidApi', 'MaterialUI'],
  //   img: `${images.p12}`,
  //   desc: `Browse Hotels Around the world `,
  // },

  {
    id: 11,
    title: 'Startup',
    category: 'react',
    url: 'https://startup.muhats.com/',
    source: 'https://github.com/coolzyte/startup',
    tags: ['React', 'Tailwind'],
    img: `${images.p3}`,
    desc: `Startup focus template`,
  },
  {
    id: 12,
    title: 'Manage Landing Page',
    category: 'react',
    url: 'https://manage-landing-page.muhats.com/',
    source: 'https://github.com/coolzyte/manage-landing-page',
    tags: ['React', 'Tailwind'],
    img: `${images.p14}`,
    desc: `Manage landing page`,
  },
  {
    id: 13,
    title: 'User Accounts Activity',
    category: 'react',
    url: 'https://frontend-interview-test.netlify.app/',
    source: 'https://github.com/coolzyte/interview-test',
    tags: ['React', 'Tailwind', 'API'],
    img: `${images.p15}`,
    desc: `User accounts analytics`,
  },
  {
    id: 14,
    title: 'Hoobank website',
    category: 'react',
    url: 'https://hoobank.muhats.com/',
    source: 'https://github.com/coolzyte/hoobank',
    tags: ['React', 'Tailwind'],
    img: `${images.p16}`,
    desc: `Hoobank react website`,
  },
  {
    id: 15,
    title: 'Pavo Website',
    category: 'react',
    url: 'https://pavo.muhats.com/',
    source: 'https://github.com/coolzyte/pavo',
    tags: ['React', 'Tailwind'],
    img: `${images.p17}`,
    desc: `Pavo react website`,
  },

  {
    id: 16,
    title: 'Dice Game',
    category: 'javascript',
    url: 'https://roll-a-dice.muhats.com/',
    source: 'https://github.com/muhammedtijani/piggame',
    tags: ['HTML5', 'CSS', 'JavaScript'],
    img: `${images.p10}`,
    desc: `Exciting Roll Dice Game `,
  },

  {
    id: 17,
    title: 'Restaurant',
    category: 'react',
    url: 'https://restaurant-app.muhats.com/',
    source: 'https://github.com/coolzyte/restaurant-app',
    tags: ['React', 'CSS'],
    img: `${images.p4}`,
    desc: `Restaurant website template `,
  },
  {
    id: 18,
    title: 'Portfolio',
    category: 'react',
    url: 'https://portfolio-v-1.muhats.com/',
    source: '',
    tags: ['React', 'styled-component'],
    img: `${images.p7}`,
    desc: `modern portfolio template`,
  },
];
export default menu;
